(source melpa)

(depends-on "ag")
(depends-on "auto-complete")
(depends-on "enh-ruby-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "pallet")
(depends-on "robe")
(depends-on "smartparens")
(depends-on "suscolors-theme")
